<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="specmodel" nsURI="http://www.example.org/specmodel" nsPrefix="specmodel">
  <eClassifiers xsi:type="ecore:EClass" name="SpecPackage" eSuperTypes="ETL_MODEL.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" upperBound="-1"
        eType="#//Specification" containment="true" eOpposite="#//Specification/specpackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specification" eSuperTypes="ETL_MODEL.ecore#//namedelement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specpackage" eType="#//SpecPackage"
        eOpposite="#//SpecPackage/specification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessrules" upperBound="-1"
        eType="#//BusinessRule" containment="true" eOpposite="#//BusinessRule/specification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primarySource" upperBound="-1"
        eType="#//Source" containment="true" eOpposite="#//Source/specification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessRule" eSuperTypes="ETL_MODEL.ecore#//namedelement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" eType="#//Specification"
        eOpposite="#//Specification/businessrules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postDedup" eType="#//Dedup"
        containment="true" eOpposite="#//Dedup/postDedupBusinessrule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preDedup" eType="#//Dedup"
        containment="true" eOpposite="#//Dedup/preDedupBusinessrule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vectorkeys" upperBound="-1"
        eType="#//VectorKey" containment="true" eOpposite="#//VectorKey/businessrule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationshipTargetEntity"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEntity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetParentEntity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lookupEntities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationshipSourceEntity"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruletype" eType="#//RuleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipTargetEntityUseHashKey"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipSourceEntityUseHashKey"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetEntityUseHashKey"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetMappingOutputFields"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceBusinessrule" eType="#//BusinessRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentSource" eType="#//Source"
        eOpposite="#//Source/childSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childSource" upperBound="-1"
        eType="#//Source" containment="true" eOpposite="#//Source/parentSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceSpecification" eType="#//Specification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" eType="#//Specification"
        eOpposite="#//Specification/primarySource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vectorkeys" upperBound="-1"
        eType="#//VectorKey" containment="true" eOpposite="#//VectorKey/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentJoinFields" upperBound="-1"
        eType="#//JoinField" containment="true" eOpposite="#//JoinField/parentSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childJoinFields" upperBound="-1"
        eType="#//JoinField" containment="true" eOpposite="#//JoinField/childSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEntity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinEntity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationship" eType="#//Relationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterField" eType="#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dedup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="postDedupBusinessrule"
        eType="#//BusinessRule" eOpposite="#//BusinessRule/postDedup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preDedupBusinessrule" eType="#//BusinessRule"
        eOpposite="#//BusinessRule/preDedup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VectorKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Source"
        eOpposite="#//Source/vectorkeys"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessrule" eType="#//BusinessRule"
        eOpposite="#//BusinessRule/vectorkeys"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentSource" eType="#//Source"
        eOpposite="#//Source/parentJoinFields"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childSource" eType="#//Source"
        eOpposite="#//Source/childJoinFields"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="ETL_MODEL.ecore#//namedelement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"
        eOpposite="#//Entity/fields"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceEntity" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="ETL_MODEL.ecore#//namedelement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Relationship" containment="true" eOpposite="#//Relationship/entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partOf" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true" eOpposite="#//Field/entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isBaselineEntityFor" eType="#//Entity"
        eOpposite="#//Entity/baselineEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baselineEntity" eType="#//Entity"
        eOpposite="#//Entity/isBaselineEntityFor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="ETL_MODEL.ecore#//namedelement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"
        eOpposite="#//Entity/relationships"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toEntity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifyingFields" upperBound="-1"
        eType="#//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="describingFields" upperBound="-1"
        eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RuleType">
    <eLiterals name="SingleFire"/>
    <eLiterals name="MultiFire" value="1"/>
    <eLiterals name="Aggregation" value="2"/>
    <eLiterals name="Filter" value="3"/>
    <eLiterals name="Dedup" value="4"/>
  </eClassifiers>
</ecore:EPackage>
