/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.specdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SpecDslStandaloneSetup extends SpecDslStandaloneSetupGenerated {

	public static void doSetup() {
		new SpecDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
