/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.etldsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ETLDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class LogpackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.logpackage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLogpackageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLogpackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLAYERKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cLAYERAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cLAYEREStringParserRuleCall_3_1_0 = (RuleCall)cLAYERAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLAYER_TYPEKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLAYER_TYPEAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLAYER_TYPELAYERTYPEEnumRuleCall_4_1_0 = (RuleCall)cLAYER_TYPEAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHISTORISATIONKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cHISTORISATIONAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cHISTORISATIONHISTORISATIONTYPEEnumRuleCall_5_1_0 = (RuleCall)cHISTORISATIONAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cREPRESENTATIONKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cREPRESENTATIONAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cREPRESENTATIONREPRESENTATIONSEnumRuleCall_6_1_0 = (RuleCall)cREPRESENTATIONAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Alternatives cAlternatives_7_0 = (Alternatives)cGroup_7.eContents().get(0);
		private final Assignment cCommonmappingAssignment_7_0_0 = (Assignment)cAlternatives_7_0.eContents().get(0);
		private final RuleCall cCommonmappingCommonMappingParserRuleCall_7_0_0_0 = (RuleCall)cCommonmappingAssignment_7_0_0.eContents().get(0);
		private final Assignment cEntityAssignment_7_0_1 = (Assignment)cAlternatives_7_0.eContents().get(1);
		private final RuleCall cEntityEntityParserRuleCall_7_0_1_0 = (RuleCall)cEntityAssignment_7_0_1.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Keyword cCommaKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Alternatives cAlternatives_7_1_1 = (Alternatives)cGroup_7_1.eContents().get(1);
		private final Assignment cCommonmappingAssignment_7_1_1_0 = (Assignment)cAlternatives_7_1_1.eContents().get(0);
		private final RuleCall cCommonmappingCommonMappingParserRuleCall_7_1_1_0_0 = (RuleCall)cCommonmappingAssignment_7_1_1_0.eContents().get(0);
		private final Assignment cEntityAssignment_7_1_1_1 = (Assignment)cAlternatives_7_1_1.eContents().get(1);
		private final RuleCall cEntityEntityParserRuleCall_7_1_1_1_0 = (RuleCall)cEntityAssignment_7_1_1_1.eContents().get(0);
		
		//logpackage:
		//	{logpackage}
		//	'logpackage' name=EString ('LAYER' LAYER=EString)? ('LAYER_TYPE' LAYER_TYPE=LAYERTYPE)? ('HISTORISATION'
		//	HISTORISATION=HISTORISATIONTYPE)? ('REPRESENTATION' REPRESENTATION=REPRESENTATIONS)? ((commonmapping+=CommonMapping |
		//	entity+=Entity) ("," (commonmapping+=CommonMapping | entity+=Entity))*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{logpackage} 'logpackage' name=EString ('LAYER' LAYER=EString)? ('LAYER_TYPE' LAYER_TYPE=LAYERTYPE)? ('HISTORISATION'
		//HISTORISATION=HISTORISATIONTYPE)? ('REPRESENTATION' REPRESENTATION=REPRESENTATIONS)? ((commonmapping+=CommonMapping |
		//entity+=Entity) ("," (commonmapping+=CommonMapping | entity+=Entity))*)?
		public Group getGroup() { return cGroup; }
		
		//{logpackage}
		public Action getLogpackageAction_0() { return cLogpackageAction_0; }
		
		//'logpackage'
		public Keyword getLogpackageKeyword_1() { return cLogpackageKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//('LAYER' LAYER=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'LAYER'
		public Keyword getLAYERKeyword_3_0() { return cLAYERKeyword_3_0; }
		
		//LAYER=EString
		public Assignment getLAYERAssignment_3_1() { return cLAYERAssignment_3_1; }
		
		//EString
		public RuleCall getLAYEREStringParserRuleCall_3_1_0() { return cLAYEREStringParserRuleCall_3_1_0; }
		
		//('LAYER_TYPE' LAYER_TYPE=LAYERTYPE)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'LAYER_TYPE'
		public Keyword getLAYER_TYPEKeyword_4_0() { return cLAYER_TYPEKeyword_4_0; }
		
		//LAYER_TYPE=LAYERTYPE
		public Assignment getLAYER_TYPEAssignment_4_1() { return cLAYER_TYPEAssignment_4_1; }
		
		//LAYERTYPE
		public RuleCall getLAYER_TYPELAYERTYPEEnumRuleCall_4_1_0() { return cLAYER_TYPELAYERTYPEEnumRuleCall_4_1_0; }
		
		//('HISTORISATION' HISTORISATION=HISTORISATIONTYPE)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'HISTORISATION'
		public Keyword getHISTORISATIONKeyword_5_0() { return cHISTORISATIONKeyword_5_0; }
		
		//HISTORISATION=HISTORISATIONTYPE
		public Assignment getHISTORISATIONAssignment_5_1() { return cHISTORISATIONAssignment_5_1; }
		
		//HISTORISATIONTYPE
		public RuleCall getHISTORISATIONHISTORISATIONTYPEEnumRuleCall_5_1_0() { return cHISTORISATIONHISTORISATIONTYPEEnumRuleCall_5_1_0; }
		
		//('REPRESENTATION' REPRESENTATION=REPRESENTATIONS)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'REPRESENTATION'
		public Keyword getREPRESENTATIONKeyword_6_0() { return cREPRESENTATIONKeyword_6_0; }
		
		//REPRESENTATION=REPRESENTATIONS
		public Assignment getREPRESENTATIONAssignment_6_1() { return cREPRESENTATIONAssignment_6_1; }
		
		//REPRESENTATIONS
		public RuleCall getREPRESENTATIONREPRESENTATIONSEnumRuleCall_6_1_0() { return cREPRESENTATIONREPRESENTATIONSEnumRuleCall_6_1_0; }
		
		//((commonmapping+=CommonMapping | entity+=Entity) ("," (commonmapping+=CommonMapping | entity+=Entity))*)?
		public Group getGroup_7() { return cGroup_7; }
		
		//(commonmapping+=CommonMapping | entity+=Entity)
		public Alternatives getAlternatives_7_0() { return cAlternatives_7_0; }
		
		//commonmapping+=CommonMapping
		public Assignment getCommonmappingAssignment_7_0_0() { return cCommonmappingAssignment_7_0_0; }
		
		//CommonMapping
		public RuleCall getCommonmappingCommonMappingParserRuleCall_7_0_0_0() { return cCommonmappingCommonMappingParserRuleCall_7_0_0_0; }
		
		//entity+=Entity
		public Assignment getEntityAssignment_7_0_1() { return cEntityAssignment_7_0_1; }
		
		//Entity
		public RuleCall getEntityEntityParserRuleCall_7_0_1_0() { return cEntityEntityParserRuleCall_7_0_1_0; }
		
		//("," (commonmapping+=CommonMapping | entity+=Entity))*
		public Group getGroup_7_1() { return cGroup_7_1; }
		
		//","
		public Keyword getCommaKeyword_7_1_0() { return cCommaKeyword_7_1_0; }
		
		//(commonmapping+=CommonMapping | entity+=Entity)
		public Alternatives getAlternatives_7_1_1() { return cAlternatives_7_1_1; }
		
		//commonmapping+=CommonMapping
		public Assignment getCommonmappingAssignment_7_1_1_0() { return cCommonmappingAssignment_7_1_1_0; }
		
		//CommonMapping
		public RuleCall getCommonmappingCommonMappingParserRuleCall_7_1_1_0_0() { return cCommonmappingCommonMappingParserRuleCall_7_1_1_0_0; }
		
		//entity+=Entity
		public Assignment getEntityAssignment_7_1_1_1() { return cEntityAssignment_7_1_1_1; }
		
		//Entity
		public RuleCall getEntityEntityParserRuleCall_7_1_1_1_0() { return cEntityEntityParserRuleCall_7_1_1_1_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class CommonMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.CommonMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommonmappingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cInputFieldKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cCommonmappinginputfieldsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cCommonmappinginputfieldsFieldParserRuleCall_3_2_0 = (RuleCall)cCommonmappinginputfieldsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cCommonmappinginputfieldsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cCommonmappinginputfieldsFieldParserRuleCall_3_3_1_0 = (RuleCall)cCommonmappinginputfieldsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOutputFieldKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCommonmappingoutputfieldsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cCommonmappingoutputfieldsFieldParserRuleCall_4_2_0 = (RuleCall)cCommonmappingoutputfieldsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cCommonmappingoutputfieldsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cCommonmappingoutputfieldsFieldParserRuleCall_4_3_1_0 = (RuleCall)cCommonmappingoutputfieldsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//CommonMapping:
		//	"commonmapping" name=ID
		//	'{' ('InputField' '{' commonmappinginputfields+=Field ("," commonmappinginputfields+=Field)* '}')? ('OutputField' '{'
		//	commonmappingoutputfields+=Field ("," commonmappingoutputfields+=Field)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//"commonmapping" name=ID '{' ('InputField' '{' commonmappinginputfields+=Field ("," commonmappinginputfields+=Field)*
		//'}')? ('OutputField' '{' commonmappingoutputfields+=Field ("," commonmappingoutputfields+=Field)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//"commonmapping"
		public Keyword getCommonmappingKeyword_0() { return cCommonmappingKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('InputField' '{' commonmappinginputfields+=Field ("," commonmappinginputfields+=Field)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'InputField'
		public Keyword getInputFieldKeyword_3_0() { return cInputFieldKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//commonmappinginputfields+=Field
		public Assignment getCommonmappinginputfieldsAssignment_3_2() { return cCommonmappinginputfieldsAssignment_3_2; }
		
		//Field
		public RuleCall getCommonmappinginputfieldsFieldParserRuleCall_3_2_0() { return cCommonmappinginputfieldsFieldParserRuleCall_3_2_0; }
		
		//("," commonmappinginputfields+=Field)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//commonmappinginputfields+=Field
		public Assignment getCommonmappinginputfieldsAssignment_3_3_1() { return cCommonmappinginputfieldsAssignment_3_3_1; }
		
		//Field
		public RuleCall getCommonmappinginputfieldsFieldParserRuleCall_3_3_1_0() { return cCommonmappinginputfieldsFieldParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('OutputField' '{' commonmappingoutputfields+=Field ("," commonmappingoutputfields+=Field)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'OutputField'
		public Keyword getOutputFieldKeyword_4_0() { return cOutputFieldKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//commonmappingoutputfields+=Field
		public Assignment getCommonmappingoutputfieldsAssignment_4_2() { return cCommonmappingoutputfieldsAssignment_4_2; }
		
		//Field
		public RuleCall getCommonmappingoutputfieldsFieldParserRuleCall_4_2_0() { return cCommonmappingoutputfieldsFieldParserRuleCall_4_2_0; }
		
		//("," commonmappingoutputfields+=Field)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//commonmappingoutputfields+=Field
		public Assignment getCommonmappingoutputfieldsAssignment_4_3_1() { return cCommonmappingoutputfieldsAssignment_4_3_1; }
		
		//Field
		public RuleCall getCommonmappingoutputfieldsFieldParserRuleCall_4_3_1_0() { return cCommonmappingoutputfieldsFieldParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEntityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEntityFieldsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEntityFieldAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cEntityFieldFieldParserRuleCall_4_2_0 = (RuleCall)cEntityFieldAssignment_4_2.eContents().get(0);
		private final Assignment cEntityFieldAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cEntityFieldFieldParserRuleCall_4_3_0 = (RuleCall)cEntityFieldAssignment_4_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIncludesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cIncludeAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cIncludeIncludeParserRuleCall_5_2_0 = (RuleCall)cIncludeAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cIncludeAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cIncludeIncludeParserRuleCall_5_3_1_0 = (RuleCall)cIncludeAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRelationshipsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRelationshipsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cRelationshipsRelationshipParserRuleCall_6_2_0 = (RuleCall)cRelationshipsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRelationshipsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cRelationshipsRelationshipParserRuleCall_6_3_1_0 = (RuleCall)cRelationshipsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Entity:
		//	{Entity}
		//	'Entity' name=ID
		//	'{' ('entityFields' '{' entityField+=Field entityField+=Field* '}')? ('Includes' '{' include+=Include (","
		//	include+=Include)* '}')? ('Relationships' '{' relationships+=Relationship ("," relationships+=Relationship)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Entity} 'Entity' name=ID '{' ('entityFields' '{' entityField+=Field entityField+=Field* '}')? ('Includes' '{'
		//include+=Include ("," include+=Include)* '}')? ('Relationships' '{' relationships+=Relationship (","
		//relationships+=Relationship)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Entity}
		public Action getEntityAction_0() { return cEntityAction_0; }
		
		//'Entity'
		public Keyword getEntityKeyword_1() { return cEntityKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('entityFields' '{' entityField+=Field entityField+=Field* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'entityFields'
		public Keyword getEntityFieldsKeyword_4_0() { return cEntityFieldsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//entityField+=Field
		public Assignment getEntityFieldAssignment_4_2() { return cEntityFieldAssignment_4_2; }
		
		//Field
		public RuleCall getEntityFieldFieldParserRuleCall_4_2_0() { return cEntityFieldFieldParserRuleCall_4_2_0; }
		
		//entityField+=Field*
		public Assignment getEntityFieldAssignment_4_3() { return cEntityFieldAssignment_4_3; }
		
		//Field
		public RuleCall getEntityFieldFieldParserRuleCall_4_3_0() { return cEntityFieldFieldParserRuleCall_4_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('Includes' '{' include+=Include ("," include+=Include)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Includes'
		public Keyword getIncludesKeyword_5_0() { return cIncludesKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//include+=Include
		public Assignment getIncludeAssignment_5_2() { return cIncludeAssignment_5_2; }
		
		//Include
		public RuleCall getIncludeIncludeParserRuleCall_5_2_0() { return cIncludeIncludeParserRuleCall_5_2_0; }
		
		//("," include+=Include)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//include+=Include
		public Assignment getIncludeAssignment_5_3_1() { return cIncludeAssignment_5_3_1; }
		
		//Include
		public RuleCall getIncludeIncludeParserRuleCall_5_3_1_0() { return cIncludeIncludeParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('Relationships' '{' relationships+=Relationship ("," relationships+=Relationship)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'Relationships'
		public Keyword getRelationshipsKeyword_6_0() { return cRelationshipsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//relationships+=Relationship
		public Assignment getRelationshipsAssignment_6_2() { return cRelationshipsAssignment_6_2; }
		
		//Relationship
		public RuleCall getRelationshipsRelationshipParserRuleCall_6_2_0() { return cRelationshipsRelationshipParserRuleCall_6_2_0; }
		
		//("," relationships+=Relationship)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//relationships+=Relationship
		public Assignment getRelationshipsAssignment_6_3_1() { return cRelationshipsAssignment_6_3_1; }
		
		//Relationship
		public RuleCall getRelationshipsRelationshipParserRuleCall_6_3_1_0() { return cRelationshipsRelationshipParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFieldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeFtEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLengthKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLengthAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLengthEIntParserRuleCall_5_1_0 = (RuleCall)cLengthAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPrecisionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPrecisionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPrecisionEIntParserRuleCall_6_1_0 = (RuleCall)cPrecisionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cScaleKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cScaleAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cScaleEIntParserRuleCall_7_1_0 = (RuleCall)cScaleAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cOriginal_nameKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cOriginal_nameAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cOriginal_nameEStringParserRuleCall_8_1_0 = (RuleCall)cOriginal_nameAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cShort_describtionKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cShort_describtionAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cShort_describtionEStringParserRuleCall_9_1_0 = (RuleCall)cShort_describtionAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cDateFormatKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cDateFormatAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cDateFormatEStringParserRuleCall_10_1_0 = (RuleCall)cDateFormatAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cNullIndicatorKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cNullIndicatorAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cNullIndicatorEStringParserRuleCall_11_1_0 = (RuleCall)cNullIndicatorAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cAllowExponentKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cAllowExponentAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cAllowExponentEBooleanParserRuleCall_12_1_0 = (RuleCall)cAllowExponentAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cHasImplicitCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cHasImplicitCommaAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cHasImplicitCommaEBooleanParserRuleCall_13_1_0 = (RuleCall)cHasImplicitCommaAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cInterfaceOnlyKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cInterfaceOnlyAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cInterfaceOnlyEBooleanParserRuleCall_14_1_0 = (RuleCall)cInterfaceOnlyAssignment_14_1.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cTableOnlyKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cTableOnlyAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cTableOnlyEBooleanParserRuleCall_15_1_0 = (RuleCall)cTableOnlyAssignment_15_1.eContents().get(0);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cIsFastChangingKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Assignment cIsFastChangingAssignment_16_1 = (Assignment)cGroup_16.eContents().get(1);
		private final RuleCall cIsFastChangingEBooleanParserRuleCall_16_1_0 = (RuleCall)cIsFastChangingAssignment_16_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//Field:
		//	{Field}
		//	"Field" name=ID
		//	"[" ("type" type=ft) ('length' length=EInt)? ('precision' precision=EInt)? ('scale' scale=EInt)? ('original_name'
		//	original_name=EString)? ('short_describtion' short_describtion=EString)? ('dateFormat' dateFormat=EString)?
		//	('NullIndicator' NullIndicator=EString)? ('allowExponent:' allowExponent?=EBoolean)? ('hasImplicitComma:'
		//	hasImplicitComma?=EBoolean)? ('interfaceOnly:' interfaceOnly?=EBoolean)? ('tableOnly:' tableOnly?=EBoolean)?
		//	('isFastChanging:' isFastChanging?=EBoolean)?
		//	"]";
		@Override public ParserRule getRule() { return rule; }
		
		//{Field} "Field" name=ID "[" ("type" type=ft) ('length' length=EInt)? ('precision' precision=EInt)? ('scale' scale=EInt)?
		//('original_name' original_name=EString)? ('short_describtion' short_describtion=EString)? ('dateFormat'
		//dateFormat=EString)? ('NullIndicator' NullIndicator=EString)? ('allowExponent:' allowExponent?=EBoolean)?
		//('hasImplicitComma:' hasImplicitComma?=EBoolean)? ('interfaceOnly:' interfaceOnly?=EBoolean)? ('tableOnly:'
		//tableOnly?=EBoolean)? ('isFastChanging:' isFastChanging?=EBoolean)? "]"
		public Group getGroup() { return cGroup; }
		
		//{Field}
		public Action getFieldAction_0() { return cFieldAction_0; }
		
		//"Field"
		public Keyword getFieldKeyword_1() { return cFieldKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_3() { return cLeftSquareBracketKeyword_3; }
		
		//("type" type=ft)
		public Group getGroup_4() { return cGroup_4; }
		
		//"type"
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=ft
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//ft
		public RuleCall getTypeFtEnumRuleCall_4_1_0() { return cTypeFtEnumRuleCall_4_1_0; }
		
		//('length' length=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'length'
		public Keyword getLengthKeyword_5_0() { return cLengthKeyword_5_0; }
		
		//length=EInt
		public Assignment getLengthAssignment_5_1() { return cLengthAssignment_5_1; }
		
		//EInt
		public RuleCall getLengthEIntParserRuleCall_5_1_0() { return cLengthEIntParserRuleCall_5_1_0; }
		
		//('precision' precision=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'precision'
		public Keyword getPrecisionKeyword_6_0() { return cPrecisionKeyword_6_0; }
		
		//precision=EInt
		public Assignment getPrecisionAssignment_6_1() { return cPrecisionAssignment_6_1; }
		
		//EInt
		public RuleCall getPrecisionEIntParserRuleCall_6_1_0() { return cPrecisionEIntParserRuleCall_6_1_0; }
		
		//('scale' scale=EInt)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'scale'
		public Keyword getScaleKeyword_7_0() { return cScaleKeyword_7_0; }
		
		//scale=EInt
		public Assignment getScaleAssignment_7_1() { return cScaleAssignment_7_1; }
		
		//EInt
		public RuleCall getScaleEIntParserRuleCall_7_1_0() { return cScaleEIntParserRuleCall_7_1_0; }
		
		//('original_name' original_name=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'original_name'
		public Keyword getOriginal_nameKeyword_8_0() { return cOriginal_nameKeyword_8_0; }
		
		//original_name=EString
		public Assignment getOriginal_nameAssignment_8_1() { return cOriginal_nameAssignment_8_1; }
		
		//EString
		public RuleCall getOriginal_nameEStringParserRuleCall_8_1_0() { return cOriginal_nameEStringParserRuleCall_8_1_0; }
		
		//('short_describtion' short_describtion=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'short_describtion'
		public Keyword getShort_describtionKeyword_9_0() { return cShort_describtionKeyword_9_0; }
		
		//short_describtion=EString
		public Assignment getShort_describtionAssignment_9_1() { return cShort_describtionAssignment_9_1; }
		
		//EString
		public RuleCall getShort_describtionEStringParserRuleCall_9_1_0() { return cShort_describtionEStringParserRuleCall_9_1_0; }
		
		//('dateFormat' dateFormat=EString)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'dateFormat'
		public Keyword getDateFormatKeyword_10_0() { return cDateFormatKeyword_10_0; }
		
		//dateFormat=EString
		public Assignment getDateFormatAssignment_10_1() { return cDateFormatAssignment_10_1; }
		
		//EString
		public RuleCall getDateFormatEStringParserRuleCall_10_1_0() { return cDateFormatEStringParserRuleCall_10_1_0; }
		
		//('NullIndicator' NullIndicator=EString)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'NullIndicator'
		public Keyword getNullIndicatorKeyword_11_0() { return cNullIndicatorKeyword_11_0; }
		
		//NullIndicator=EString
		public Assignment getNullIndicatorAssignment_11_1() { return cNullIndicatorAssignment_11_1; }
		
		//EString
		public RuleCall getNullIndicatorEStringParserRuleCall_11_1_0() { return cNullIndicatorEStringParserRuleCall_11_1_0; }
		
		//('allowExponent:' allowExponent?=EBoolean)?
		public Group getGroup_12() { return cGroup_12; }
		
		//'allowExponent:'
		public Keyword getAllowExponentKeyword_12_0() { return cAllowExponentKeyword_12_0; }
		
		//allowExponent?=EBoolean
		public Assignment getAllowExponentAssignment_12_1() { return cAllowExponentAssignment_12_1; }
		
		//EBoolean
		public RuleCall getAllowExponentEBooleanParserRuleCall_12_1_0() { return cAllowExponentEBooleanParserRuleCall_12_1_0; }
		
		//('hasImplicitComma:' hasImplicitComma?=EBoolean)?
		public Group getGroup_13() { return cGroup_13; }
		
		//'hasImplicitComma:'
		public Keyword getHasImplicitCommaKeyword_13_0() { return cHasImplicitCommaKeyword_13_0; }
		
		//hasImplicitComma?=EBoolean
		public Assignment getHasImplicitCommaAssignment_13_1() { return cHasImplicitCommaAssignment_13_1; }
		
		//EBoolean
		public RuleCall getHasImplicitCommaEBooleanParserRuleCall_13_1_0() { return cHasImplicitCommaEBooleanParserRuleCall_13_1_0; }
		
		//('interfaceOnly:' interfaceOnly?=EBoolean)?
		public Group getGroup_14() { return cGroup_14; }
		
		//'interfaceOnly:'
		public Keyword getInterfaceOnlyKeyword_14_0() { return cInterfaceOnlyKeyword_14_0; }
		
		//interfaceOnly?=EBoolean
		public Assignment getInterfaceOnlyAssignment_14_1() { return cInterfaceOnlyAssignment_14_1; }
		
		//EBoolean
		public RuleCall getInterfaceOnlyEBooleanParserRuleCall_14_1_0() { return cInterfaceOnlyEBooleanParserRuleCall_14_1_0; }
		
		//('tableOnly:' tableOnly?=EBoolean)?
		public Group getGroup_15() { return cGroup_15; }
		
		//'tableOnly:'
		public Keyword getTableOnlyKeyword_15_0() { return cTableOnlyKeyword_15_0; }
		
		//tableOnly?=EBoolean
		public Assignment getTableOnlyAssignment_15_1() { return cTableOnlyAssignment_15_1; }
		
		//EBoolean
		public RuleCall getTableOnlyEBooleanParserRuleCall_15_1_0() { return cTableOnlyEBooleanParserRuleCall_15_1_0; }
		
		//('isFastChanging:' isFastChanging?=EBoolean)?
		public Group getGroup_16() { return cGroup_16; }
		
		//'isFastChanging:'
		public Keyword getIsFastChangingKeyword_16_0() { return cIsFastChangingKeyword_16_0; }
		
		//isFastChanging?=EBoolean
		public Assignment getIsFastChangingAssignment_16_1() { return cIsFastChangingAssignment_16_1; }
		
		//EBoolean
		public RuleCall getIsFastChangingEBooleanParserRuleCall_16_1_0() { return cIsFastChangingEBooleanParserRuleCall_16_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_17() { return cRightSquareBracketKeyword_17; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class IncludeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.Include");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIncludeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cIncludeFieldsKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cIncludeFieldsAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final CrossReference cIncludeFieldsFieldCrossReference_2_1_2_0 = (CrossReference)cIncludeFieldsAssignment_2_1_2.eContents().get(0);
		private final RuleCall cIncludeFieldsFieldQualifiedNameParserRuleCall_2_1_2_0_1 = (RuleCall)cIncludeFieldsFieldCrossReference_2_1_2_0.eContents().get(1);
		private final Group cGroup_2_1_3 = (Group)cGroup_2_1.eContents().get(3);
		private final Keyword cCommaKeyword_2_1_3_0 = (Keyword)cGroup_2_1_3.eContents().get(0);
		private final Assignment cIncludeFieldsAssignment_2_1_3_1 = (Assignment)cGroup_2_1_3.eContents().get(1);
		private final CrossReference cIncludeFieldsFieldCrossReference_2_1_3_1_0 = (CrossReference)cIncludeFieldsAssignment_2_1_3_1.eContents().get(0);
		private final RuleCall cIncludeFieldsFieldQualifiedNameParserRuleCall_2_1_3_1_0_1 = (RuleCall)cIncludeFieldsFieldCrossReference_2_1_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_2_1_4 = (Keyword)cGroup_2_1.eContents().get(4);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cIdentifyingFieldsKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cIdentifyingfieldsAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final CrossReference cIdentifyingfieldsFieldCrossReference_2_2_1_0 = (CrossReference)cIdentifyingfieldsAssignment_2_2_1.eContents().get(0);
		private final RuleCall cIdentifyingfieldsFieldQualifiedNameParserRuleCall_2_2_1_0_1 = (RuleCall)cIdentifyingfieldsFieldCrossReference_2_2_1_0.eContents().get(1);
		private final Group cGroup_2_2_2 = (Group)cGroup_2_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_2_0 = (Keyword)cGroup_2_2_2.eContents().get(0);
		private final Assignment cIdentifyingfieldsAssignment_2_2_2_1 = (Assignment)cGroup_2_2_2.eContents().get(1);
		private final CrossReference cIdentifyingfieldsFieldCrossReference_2_2_2_1_0 = (CrossReference)cIdentifyingfieldsAssignment_2_2_2_1.eContents().get(0);
		private final RuleCall cIdentifyingfieldsFieldQualifiedNameParserRuleCall_2_2_2_1_0_1 = (RuleCall)cIdentifyingfieldsFieldCrossReference_2_2_2_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_2_2_3 = (Keyword)cGroup_2_2.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//Include:
		//	'Include' name=EString ('{' ('IncludeFields' '{' includeFields+=[Field|QualifiedName] (","
		//	includeFields+=[Field|QualifiedName])* '}')? ('IdentifyingFields:{' identifyingfields+=[Field|QualifiedName] (','
		//	identifyingfields+=[Field|QualifiedName])* '}')?
		//	'}');
		@Override public ParserRule getRule() { return rule; }
		
		//'Include' name=EString ('{' ('IncludeFields' '{' includeFields+=[Field|QualifiedName] (","
		//includeFields+=[Field|QualifiedName])* '}')? ('IdentifyingFields:{' identifyingfields+=[Field|QualifiedName] (','
		//identifyingfields+=[Field|QualifiedName])* '}')? '}')
		public Group getGroup() { return cGroup; }
		
		//'Include'
		public Keyword getIncludeKeyword_0() { return cIncludeKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('{' ('IncludeFields' '{' includeFields+=[Field|QualifiedName] ("," includeFields+=[Field|QualifiedName])* '}')?
		//('IdentifyingFields:{' identifyingfields+=[Field|QualifiedName] (',' identifyingfields+=[Field|QualifiedName])* '}')?
		//'}')
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('IncludeFields' '{' includeFields+=[Field|QualifiedName] ("," includeFields+=[Field|QualifiedName])* '}')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'IncludeFields'
		public Keyword getIncludeFieldsKeyword_2_1_0() { return cIncludeFieldsKeyword_2_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_1_1() { return cLeftCurlyBracketKeyword_2_1_1; }
		
		//includeFields+=[Field|QualifiedName]
		public Assignment getIncludeFieldsAssignment_2_1_2() { return cIncludeFieldsAssignment_2_1_2; }
		
		//[Field|QualifiedName]
		public CrossReference getIncludeFieldsFieldCrossReference_2_1_2_0() { return cIncludeFieldsFieldCrossReference_2_1_2_0; }
		
		//QualifiedName
		public RuleCall getIncludeFieldsFieldQualifiedNameParserRuleCall_2_1_2_0_1() { return cIncludeFieldsFieldQualifiedNameParserRuleCall_2_1_2_0_1; }
		
		//("," includeFields+=[Field|QualifiedName])*
		public Group getGroup_2_1_3() { return cGroup_2_1_3; }
		
		//","
		public Keyword getCommaKeyword_2_1_3_0() { return cCommaKeyword_2_1_3_0; }
		
		//includeFields+=[Field|QualifiedName]
		public Assignment getIncludeFieldsAssignment_2_1_3_1() { return cIncludeFieldsAssignment_2_1_3_1; }
		
		//[Field|QualifiedName]
		public CrossReference getIncludeFieldsFieldCrossReference_2_1_3_1_0() { return cIncludeFieldsFieldCrossReference_2_1_3_1_0; }
		
		//QualifiedName
		public RuleCall getIncludeFieldsFieldQualifiedNameParserRuleCall_2_1_3_1_0_1() { return cIncludeFieldsFieldQualifiedNameParserRuleCall_2_1_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_1_4() { return cRightCurlyBracketKeyword_2_1_4; }
		
		//('IdentifyingFields:{' identifyingfields+=[Field|QualifiedName] (',' identifyingfields+=[Field|QualifiedName])* '}')?
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'IdentifyingFields:{'
		public Keyword getIdentifyingFieldsKeyword_2_2_0() { return cIdentifyingFieldsKeyword_2_2_0; }
		
		//identifyingfields+=[Field|QualifiedName]
		public Assignment getIdentifyingfieldsAssignment_2_2_1() { return cIdentifyingfieldsAssignment_2_2_1; }
		
		//[Field|QualifiedName]
		public CrossReference getIdentifyingfieldsFieldCrossReference_2_2_1_0() { return cIdentifyingfieldsFieldCrossReference_2_2_1_0; }
		
		//QualifiedName
		public RuleCall getIdentifyingfieldsFieldQualifiedNameParserRuleCall_2_2_1_0_1() { return cIdentifyingfieldsFieldQualifiedNameParserRuleCall_2_2_1_0_1; }
		
		//(',' identifyingfields+=[Field|QualifiedName])*
		public Group getGroup_2_2_2() { return cGroup_2_2_2; }
		
		//','
		public Keyword getCommaKeyword_2_2_2_0() { return cCommaKeyword_2_2_2_0; }
		
		//identifyingfields+=[Field|QualifiedName]
		public Assignment getIdentifyingfieldsAssignment_2_2_2_1() { return cIdentifyingfieldsAssignment_2_2_2_1; }
		
		//[Field|QualifiedName]
		public CrossReference getIdentifyingfieldsFieldCrossReference_2_2_2_1_0() { return cIdentifyingfieldsFieldCrossReference_2_2_2_1_0; }
		
		//QualifiedName
		public RuleCall getIdentifyingfieldsFieldQualifiedNameParserRuleCall_2_2_2_1_0_1() { return cIdentifyingfieldsFieldQualifiedNameParserRuleCall_2_2_2_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_2_3() { return cRightCurlyBracketKeyword_2_2_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }
	}
	public class RelationshipElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.Relationship");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRelationshipAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRelationshipKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cToEntityKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cToEntityAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cToEntityEntityCrossReference_5_0 = (CrossReference)cToEntityAssignment_5.eContents().get(0);
		private final RuleCall cToEntityEntityQualifiedNameParserRuleCall_5_0_1 = (RuleCall)cToEntityEntityCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescribingFieldsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescribingFieldsRelAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cDescribingFieldsRelFieldCrossReference_6_1_0 = (CrossReference)cDescribingFieldsRelAssignment_6_1.eContents().get(0);
		private final RuleCall cDescribingFieldsRelFieldQualifiedNameParserRuleCall_6_1_0_1 = (RuleCall)cDescribingFieldsRelFieldCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_6_2 = (Group)cGroup_6.eContents().get(2);
		private final Keyword cCommaKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final Assignment cDescribingFieldsRelAssignment_6_2_1 = (Assignment)cGroup_6_2.eContents().get(1);
		private final CrossReference cDescribingFieldsRelFieldCrossReference_6_2_1_0 = (CrossReference)cDescribingFieldsRelAssignment_6_2_1.eContents().get(0);
		private final RuleCall cDescribingFieldsRelFieldQualifiedNameParserRuleCall_6_2_1_0_1 = (RuleCall)cDescribingFieldsRelFieldCrossReference_6_2_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIdentifyingFieldsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIdentifiyingFieldsRelAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cIdentifiyingFieldsRelFieldCrossReference_7_1_0 = (CrossReference)cIdentifiyingFieldsRelAssignment_7_1.eContents().get(0);
		private final RuleCall cIdentifiyingFieldsRelFieldQualifiedNameParserRuleCall_7_1_0_1 = (RuleCall)cIdentifiyingFieldsRelFieldCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cCommaKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cIdentifiyingFieldsRelAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final CrossReference cIdentifiyingFieldsRelFieldCrossReference_7_2_1_0 = (CrossReference)cIdentifiyingFieldsRelAssignment_7_2_1.eContents().get(0);
		private final RuleCall cIdentifiyingFieldsRelFieldQualifiedNameParserRuleCall_7_2_1_0_1 = (RuleCall)cIdentifiyingFieldsRelFieldCrossReference_7_2_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Relationship:
		//	{Relationship}
		//	'Relationship' name=EString
		//	'{'
		//	'ToEntity: ' toEntity=[Entity|QualifiedName] ('DescribingFields:{' describingFieldsRel+=[Field|QualifiedName] (','
		//	describingFieldsRel+=[Field|QualifiedName])* '}')? ('IdentifyingFields:{'
		//	identifiyingFieldsRel+=[Field|QualifiedName] (',' identifiyingFieldsRel+=[Field|QualifiedName])* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Relationship} 'Relationship' name=EString '{' 'ToEntity: ' toEntity=[Entity|QualifiedName] ('DescribingFields:{'
		//describingFieldsRel+=[Field|QualifiedName] (',' describingFieldsRel+=[Field|QualifiedName])* '}')?
		//('IdentifyingFields:{' identifiyingFieldsRel+=[Field|QualifiedName] (','
		//identifiyingFieldsRel+=[Field|QualifiedName])* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Relationship}
		public Action getRelationshipAction_0() { return cRelationshipAction_0; }
		
		//'Relationship'
		public Keyword getRelationshipKeyword_1() { return cRelationshipKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'ToEntity: '
		public Keyword getToEntityKeyword_4() { return cToEntityKeyword_4; }
		
		//toEntity=[Entity|QualifiedName]
		public Assignment getToEntityAssignment_5() { return cToEntityAssignment_5; }
		
		//[Entity|QualifiedName]
		public CrossReference getToEntityEntityCrossReference_5_0() { return cToEntityEntityCrossReference_5_0; }
		
		//QualifiedName
		public RuleCall getToEntityEntityQualifiedNameParserRuleCall_5_0_1() { return cToEntityEntityQualifiedNameParserRuleCall_5_0_1; }
		
		//('DescribingFields:{' describingFieldsRel+=[Field|QualifiedName] (',' describingFieldsRel+=[Field|QualifiedName])* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'DescribingFields:{'
		public Keyword getDescribingFieldsKeyword_6_0() { return cDescribingFieldsKeyword_6_0; }
		
		//describingFieldsRel+=[Field|QualifiedName]
		public Assignment getDescribingFieldsRelAssignment_6_1() { return cDescribingFieldsRelAssignment_6_1; }
		
		//[Field|QualifiedName]
		public CrossReference getDescribingFieldsRelFieldCrossReference_6_1_0() { return cDescribingFieldsRelFieldCrossReference_6_1_0; }
		
		//QualifiedName
		public RuleCall getDescribingFieldsRelFieldQualifiedNameParserRuleCall_6_1_0_1() { return cDescribingFieldsRelFieldQualifiedNameParserRuleCall_6_1_0_1; }
		
		//(',' describingFieldsRel+=[Field|QualifiedName])*
		public Group getGroup_6_2() { return cGroup_6_2; }
		
		//','
		public Keyword getCommaKeyword_6_2_0() { return cCommaKeyword_6_2_0; }
		
		//describingFieldsRel+=[Field|QualifiedName]
		public Assignment getDescribingFieldsRelAssignment_6_2_1() { return cDescribingFieldsRelAssignment_6_2_1; }
		
		//[Field|QualifiedName]
		public CrossReference getDescribingFieldsRelFieldCrossReference_6_2_1_0() { return cDescribingFieldsRelFieldCrossReference_6_2_1_0; }
		
		//QualifiedName
		public RuleCall getDescribingFieldsRelFieldQualifiedNameParserRuleCall_6_2_1_0_1() { return cDescribingFieldsRelFieldQualifiedNameParserRuleCall_6_2_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_3() { return cRightCurlyBracketKeyword_6_3; }
		
		//('IdentifyingFields:{' identifiyingFieldsRel+=[Field|QualifiedName] (',' identifiyingFieldsRel+=[Field|QualifiedName])*
		//'}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'IdentifyingFields:{'
		public Keyword getIdentifyingFieldsKeyword_7_0() { return cIdentifyingFieldsKeyword_7_0; }
		
		//identifiyingFieldsRel+=[Field|QualifiedName]
		public Assignment getIdentifiyingFieldsRelAssignment_7_1() { return cIdentifiyingFieldsRelAssignment_7_1; }
		
		//[Field|QualifiedName]
		public CrossReference getIdentifiyingFieldsRelFieldCrossReference_7_1_0() { return cIdentifiyingFieldsRelFieldCrossReference_7_1_0; }
		
		//QualifiedName
		public RuleCall getIdentifiyingFieldsRelFieldQualifiedNameParserRuleCall_7_1_0_1() { return cIdentifiyingFieldsRelFieldQualifiedNameParserRuleCall_7_1_0_1; }
		
		//(',' identifiyingFieldsRel+=[Field|QualifiedName])*
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//','
		public Keyword getCommaKeyword_7_2_0() { return cCommaKeyword_7_2_0; }
		
		//identifiyingFieldsRel+=[Field|QualifiedName]
		public Assignment getIdentifiyingFieldsRelAssignment_7_2_1() { return cIdentifiyingFieldsRelAssignment_7_2_1; }
		
		//[Field|QualifiedName]
		public CrossReference getIdentifiyingFieldsRelFieldCrossReference_7_2_1_0() { return cIdentifiyingFieldsRelFieldCrossReference_7_2_1_0; }
		
		//QualifiedName
		public RuleCall getIdentifiyingFieldsRelFieldQualifiedNameParserRuleCall_7_2_1_0_1() { return cIdentifiyingFieldsRelFieldQualifiedNameParserRuleCall_7_2_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	public class LAYERTYPEElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.LAYERTYPE");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTAGEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTAGESTAGEKeyword_0_0 = (Keyword)cSTAGEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cINTEGRATIONEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cINTEGRATIONINTEGRATIONKeyword_1_0 = (Keyword)cINTEGRATIONEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cEXPORTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cEXPORTEXPORTKeyword_2_0 = (Keyword)cEXPORTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cREPORTINGEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cREPORTINGREPORTINGKeyword_3_0 = (Keyword)cREPORTINGEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cHARMONISATIONEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cHARMONISATIONHARMONISATIONKeyword_4_0 = (Keyword)cHARMONISATIONEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum LAYERTYPE returns package_enums::LAYERTYPE:
		//	STAGE | INTEGRATION | EXPORT | REPORTING | HARMONISATION;
		public EnumRule getRule() { return rule; }
		
		//STAGE | INTEGRATION | EXPORT | REPORTING | HARMONISATION
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STAGE
		public EnumLiteralDeclaration getSTAGEEnumLiteralDeclaration_0() { return cSTAGEEnumLiteralDeclaration_0; }
		
		//'STAGE'
		public Keyword getSTAGESTAGEKeyword_0_0() { return cSTAGESTAGEKeyword_0_0; }
		
		//INTEGRATION
		public EnumLiteralDeclaration getINTEGRATIONEnumLiteralDeclaration_1() { return cINTEGRATIONEnumLiteralDeclaration_1; }
		
		//'INTEGRATION'
		public Keyword getINTEGRATIONINTEGRATIONKeyword_1_0() { return cINTEGRATIONINTEGRATIONKeyword_1_0; }
		
		//EXPORT
		public EnumLiteralDeclaration getEXPORTEnumLiteralDeclaration_2() { return cEXPORTEnumLiteralDeclaration_2; }
		
		//'EXPORT'
		public Keyword getEXPORTEXPORTKeyword_2_0() { return cEXPORTEXPORTKeyword_2_0; }
		
		//REPORTING
		public EnumLiteralDeclaration getREPORTINGEnumLiteralDeclaration_3() { return cREPORTINGEnumLiteralDeclaration_3; }
		
		//'REPORTING'
		public Keyword getREPORTINGREPORTINGKeyword_3_0() { return cREPORTINGREPORTINGKeyword_3_0; }
		
		//HARMONISATION
		public EnumLiteralDeclaration getHARMONISATIONEnumLiteralDeclaration_4() { return cHARMONISATIONEnumLiteralDeclaration_4; }
		
		//'HARMONISATION'
		public Keyword getHARMONISATIONHARMONISATIONKeyword_4_0() { return cHARMONISATIONHARMONISATIONKeyword_4_0; }
	}
	public class HISTORISATIONTYPEElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.HISTORISATIONTYPE");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNONEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNONENONEKeyword_0_0 = (Keyword)cNONEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDAY_PARTITIONEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDAY_PARTITIONEDDAY_PARTITIONEDKeyword_1_0 = (Keyword)cDAY_PARTITIONEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMONTH_PARTITIONEDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMONTH_PARTITIONEDMONTH_PARTITIONEDKeyword_2_0 = (Keyword)cMONTH_PARTITIONEDEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cBITEMPORALEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cBITEMPORALBITEMPORALKeyword_3_0 = (Keyword)cBITEMPORALEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum HISTORISATIONTYPE returns package_enums::HISTORISATIONTYPE:
		//	NONE | DAY_PARTITIONED | MONTH_PARTITIONED | BITEMPORAL;
		public EnumRule getRule() { return rule; }
		
		//NONE | DAY_PARTITIONED | MONTH_PARTITIONED | BITEMPORAL
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NONE
		public EnumLiteralDeclaration getNONEEnumLiteralDeclaration_0() { return cNONEEnumLiteralDeclaration_0; }
		
		//'NONE'
		public Keyword getNONENONEKeyword_0_0() { return cNONENONEKeyword_0_0; }
		
		//DAY_PARTITIONED
		public EnumLiteralDeclaration getDAY_PARTITIONEDEnumLiteralDeclaration_1() { return cDAY_PARTITIONEDEnumLiteralDeclaration_1; }
		
		//'DAY_PARTITIONED'
		public Keyword getDAY_PARTITIONEDDAY_PARTITIONEDKeyword_1_0() { return cDAY_PARTITIONEDDAY_PARTITIONEDKeyword_1_0; }
		
		//MONTH_PARTITIONED
		public EnumLiteralDeclaration getMONTH_PARTITIONEDEnumLiteralDeclaration_2() { return cMONTH_PARTITIONEDEnumLiteralDeclaration_2; }
		
		//'MONTH_PARTITIONED'
		public Keyword getMONTH_PARTITIONEDMONTH_PARTITIONEDKeyword_2_0() { return cMONTH_PARTITIONEDMONTH_PARTITIONEDKeyword_2_0; }
		
		//BITEMPORAL
		public EnumLiteralDeclaration getBITEMPORALEnumLiteralDeclaration_3() { return cBITEMPORALEnumLiteralDeclaration_3; }
		
		//'BITEMPORAL'
		public Keyword getBITEMPORALBITEMPORALKeyword_3_0() { return cBITEMPORALBITEMPORALKeyword_3_0; }
	}
	public class REPRESENTATIONSElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.REPRESENTATIONS");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFLAT_TABLEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFLAT_TABLEFLAT_TABLEKeyword_0_0 = (Keyword)cFLAT_TABLEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDATAVAULTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDATAVAULTDATAVAULTKeyword_1_0 = (Keyword)cDATAVAULTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cThirdNFEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cThirdNFThirdNFKeyword_2_0 = (Keyword)cThirdNFEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSNOWFLAKEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSNOWFLAKESNOWFLAKEKeyword_3_0 = (Keyword)cSNOWFLAKEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cSTAREnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cSTARSTARKeyword_4_0 = (Keyword)cSTAREnumLiteralDeclaration_4.eContents().get(0);
		
		//enum REPRESENTATIONS returns package_enums::REPRESENTATIONS:
		//	FLAT_TABLE | DATAVAULT | ThirdNF | SNOWFLAKE | STAR;
		public EnumRule getRule() { return rule; }
		
		//FLAT_TABLE | DATAVAULT | ThirdNF | SNOWFLAKE | STAR
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FLAT_TABLE
		public EnumLiteralDeclaration getFLAT_TABLEEnumLiteralDeclaration_0() { return cFLAT_TABLEEnumLiteralDeclaration_0; }
		
		//'FLAT_TABLE'
		public Keyword getFLAT_TABLEFLAT_TABLEKeyword_0_0() { return cFLAT_TABLEFLAT_TABLEKeyword_0_0; }
		
		//DATAVAULT
		public EnumLiteralDeclaration getDATAVAULTEnumLiteralDeclaration_1() { return cDATAVAULTEnumLiteralDeclaration_1; }
		
		//'DATAVAULT'
		public Keyword getDATAVAULTDATAVAULTKeyword_1_0() { return cDATAVAULTDATAVAULTKeyword_1_0; }
		
		//ThirdNF
		public EnumLiteralDeclaration getThirdNFEnumLiteralDeclaration_2() { return cThirdNFEnumLiteralDeclaration_2; }
		
		//'ThirdNF'
		public Keyword getThirdNFThirdNFKeyword_2_0() { return cThirdNFThirdNFKeyword_2_0; }
		
		//SNOWFLAKE
		public EnumLiteralDeclaration getSNOWFLAKEEnumLiteralDeclaration_3() { return cSNOWFLAKEEnumLiteralDeclaration_3; }
		
		//'SNOWFLAKE'
		public Keyword getSNOWFLAKESNOWFLAKEKeyword_3_0() { return cSNOWFLAKESNOWFLAKEKeyword_3_0; }
		
		//STAR
		public EnumLiteralDeclaration getSTAREnumLiteralDeclaration_4() { return cSTAREnumLiteralDeclaration_4; }
		
		//'STAR'
		public Keyword getSTARSTARKeyword_4_0() { return cSTARSTARKeyword_4_0; }
	}
	public class FtElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.etl_modeling.etldsl.ETLDsl.ft");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStringStringKeyword_0_0 = (Keyword)cStringEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDateEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDateDateKeyword_1_0 = (Keyword)cDateEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDecimalEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDecimalDecimalKeyword_2_0 = (Keyword)cDecimalEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cHKEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cHKHKKeyword_3_0 = (Keyword)cHKEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cIntIntKeyword_4_0 = (Keyword)cIntEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cTimeStampEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cTimeStampTimeStampKeyword_5_0 = (Keyword)cTimeStampEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cTrueFalseEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cTrueFalseTrueFalseKeyword_6_0 = (Keyword)cTrueFalseEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum ft returns type_enums::FieldTypes:
		//	String | Date | Decimal | HK | Int | TimeStamp | TrueFalse;
		public EnumRule getRule() { return rule; }
		
		//String | Date | Decimal | HK | Int | TimeStamp | TrueFalse
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//String
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_0() { return cStringEnumLiteralDeclaration_0; }
		
		//'String'
		public Keyword getStringStringKeyword_0_0() { return cStringStringKeyword_0_0; }
		
		//Date
		public EnumLiteralDeclaration getDateEnumLiteralDeclaration_1() { return cDateEnumLiteralDeclaration_1; }
		
		//'Date'
		public Keyword getDateDateKeyword_1_0() { return cDateDateKeyword_1_0; }
		
		//Decimal
		public EnumLiteralDeclaration getDecimalEnumLiteralDeclaration_2() { return cDecimalEnumLiteralDeclaration_2; }
		
		//'Decimal'
		public Keyword getDecimalDecimalKeyword_2_0() { return cDecimalDecimalKeyword_2_0; }
		
		//HK
		public EnumLiteralDeclaration getHKEnumLiteralDeclaration_3() { return cHKEnumLiteralDeclaration_3; }
		
		//'HK'
		public Keyword getHKHKKeyword_3_0() { return cHKHKKeyword_3_0; }
		
		//Int
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_4() { return cIntEnumLiteralDeclaration_4; }
		
		//'Int'
		public Keyword getIntIntKeyword_4_0() { return cIntIntKeyword_4_0; }
		
		//TimeStamp
		public EnumLiteralDeclaration getTimeStampEnumLiteralDeclaration_5() { return cTimeStampEnumLiteralDeclaration_5; }
		
		//'TimeStamp'
		public Keyword getTimeStampTimeStampKeyword_5_0() { return cTimeStampTimeStampKeyword_5_0; }
		
		//TrueFalse
		public EnumLiteralDeclaration getTrueFalseEnumLiteralDeclaration_6() { return cTrueFalseEnumLiteralDeclaration_6; }
		
		//'TrueFalse'
		public Keyword getTrueFalseTrueFalseKeyword_6_0() { return cTrueFalseTrueFalseKeyword_6_0; }
	}
	
	private final LogpackageElements pLogpackage;
	private final EStringElements pEString;
	private final LAYERTYPEElements eLAYERTYPE;
	private final HISTORISATIONTYPEElements eHISTORISATIONTYPE;
	private final REPRESENTATIONSElements eREPRESENTATIONS;
	private final CommonMappingElements pCommonMapping;
	private final EntityElements pEntity;
	private final FieldElements pField;
	private final QualifiedNameElements pQualifiedName;
	private final EIntElements pEInt;
	private final EBooleanElements pEBoolean;
	private final FtElements eFt;
	private final IncludeElements pInclude;
	private final RelationshipElements pRelationship;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ETLDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pLogpackage = new LogpackageElements();
		this.pEString = new EStringElements();
		this.eLAYERTYPE = new LAYERTYPEElements();
		this.eHISTORISATIONTYPE = new HISTORISATIONTYPEElements();
		this.eREPRESENTATIONS = new REPRESENTATIONSElements();
		this.pCommonMapping = new CommonMappingElements();
		this.pEntity = new EntityElements();
		this.pField = new FieldElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pEInt = new EIntElements();
		this.pEBoolean = new EBooleanElements();
		this.eFt = new FtElements();
		this.pInclude = new IncludeElements();
		this.pRelationship = new RelationshipElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.etl_modeling.etldsl.ETLDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//logpackage:
	//	{logpackage}
	//	'logpackage' name=EString ('LAYER' LAYER=EString)? ('LAYER_TYPE' LAYER_TYPE=LAYERTYPE)? ('HISTORISATION'
	//	HISTORISATION=HISTORISATIONTYPE)? ('REPRESENTATION' REPRESENTATION=REPRESENTATIONS)? ((commonmapping+=CommonMapping |
	//	entity+=Entity) ("," (commonmapping+=CommonMapping | entity+=Entity))*)?;
	public LogpackageElements getLogpackageAccess() {
		return pLogpackage;
	}
	
	public ParserRule getLogpackageRule() {
		return getLogpackageAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum LAYERTYPE returns package_enums::LAYERTYPE:
	//	STAGE | INTEGRATION | EXPORT | REPORTING | HARMONISATION;
	public LAYERTYPEElements getLAYERTYPEAccess() {
		return eLAYERTYPE;
	}
	
	public EnumRule getLAYERTYPERule() {
		return getLAYERTYPEAccess().getRule();
	}
	
	//enum HISTORISATIONTYPE returns package_enums::HISTORISATIONTYPE:
	//	NONE | DAY_PARTITIONED | MONTH_PARTITIONED | BITEMPORAL;
	public HISTORISATIONTYPEElements getHISTORISATIONTYPEAccess() {
		return eHISTORISATIONTYPE;
	}
	
	public EnumRule getHISTORISATIONTYPERule() {
		return getHISTORISATIONTYPEAccess().getRule();
	}
	
	//enum REPRESENTATIONS returns package_enums::REPRESENTATIONS:
	//	FLAT_TABLE | DATAVAULT | ThirdNF | SNOWFLAKE | STAR;
	public REPRESENTATIONSElements getREPRESENTATIONSAccess() {
		return eREPRESENTATIONS;
	}
	
	public EnumRule getREPRESENTATIONSRule() {
		return getREPRESENTATIONSAccess().getRule();
	}
	
	//CommonMapping:
	//	"commonmapping" name=ID
	//	'{' ('InputField' '{' commonmappinginputfields+=Field ("," commonmappinginputfields+=Field)* '}')? ('OutputField' '{'
	//	commonmappingoutputfields+=Field ("," commonmappingoutputfields+=Field)* '}')?
	//	'}';
	public CommonMappingElements getCommonMappingAccess() {
		return pCommonMapping;
	}
	
	public ParserRule getCommonMappingRule() {
		return getCommonMappingAccess().getRule();
	}
	
	//Entity:
	//	{Entity}
	//	'Entity' name=ID
	//	'{' ('entityFields' '{' entityField+=Field entityField+=Field* '}')? ('Includes' '{' include+=Include (","
	//	include+=Include)* '}')? ('Relationships' '{' relationships+=Relationship ("," relationships+=Relationship)* '}')?
	//	'}';
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//Field:
	//	{Field}
	//	"Field" name=ID
	//	"[" ("type" type=ft) ('length' length=EInt)? ('precision' precision=EInt)? ('scale' scale=EInt)? ('original_name'
	//	original_name=EString)? ('short_describtion' short_describtion=EString)? ('dateFormat' dateFormat=EString)?
	//	('NullIndicator' NullIndicator=EString)? ('allowExponent:' allowExponent?=EBoolean)? ('hasImplicitComma:'
	//	hasImplicitComma?=EBoolean)? ('interfaceOnly:' interfaceOnly?=EBoolean)? ('tableOnly:' tableOnly?=EBoolean)?
	//	('isFastChanging:' isFastChanging?=EBoolean)?
	//	"]";
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//enum ft returns type_enums::FieldTypes:
	//	String | Date | Decimal | HK | Int | TimeStamp | TrueFalse;
	public FtElements getFtAccess() {
		return eFt;
	}
	
	public EnumRule getFtRule() {
		return getFtAccess().getRule();
	}
	
	//Include:
	//	'Include' name=EString ('{' ('IncludeFields' '{' includeFields+=[Field|QualifiedName] (","
	//	includeFields+=[Field|QualifiedName])* '}')? ('IdentifyingFields:{' identifyingfields+=[Field|QualifiedName] (','
	//	identifyingfields+=[Field|QualifiedName])* '}')?
	//	'}');
	public IncludeElements getIncludeAccess() {
		return pInclude;
	}
	
	public ParserRule getIncludeRule() {
		return getIncludeAccess().getRule();
	}
	
	//Relationship:
	//	{Relationship}
	//	'Relationship' name=EString
	//	'{'
	//	'ToEntity: ' toEntity=[Entity|QualifiedName] ('DescribingFields:{' describingFieldsRel+=[Field|QualifiedName] (','
	//	describingFieldsRel+=[Field|QualifiedName])* '}')? ('IdentifyingFields:{'
	//	identifiyingFieldsRel+=[Field|QualifiedName] (',' identifiyingFieldsRel+=[Field|QualifiedName])* '}')?
	//	'}';
	public RelationshipElements getRelationshipAccess() {
		return pRelationship;
	}
	
	public ParserRule getRelationshipRule() {
		return getRelationshipAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
