/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.jobdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.etl_modeling.jobdsl.parser.antlr.internal.InternalJobDslParser;
import org.etl_modeling.jobdsl.services.JobDslGrammarAccess;

public class JobDslParser extends AbstractAntlrParser {

	@Inject
	private JobDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJobDslParser createParser(XtextTokenStream stream) {
		return new InternalJobDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SchedulePackage";
	}

	public JobDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JobDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
