/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.jobdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JobDslUiModule extends AbstractJobDslUiModule {

	public JobDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
