/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.specdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpecDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/etl_modeling/specdsl/parser/antlr/internal/InternalSpecDsl.tokens");
	}
}
