/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.etldsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractETLDslScopeProvider extends DelegatingScopeProvider {
}
