/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.specdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SpecDslUiModule extends AbstractSpecDslUiModule {

	public SpecDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
