/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.etldsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.etl_modeling.etldsl.ui.internal.EtldslActivator;

public class ETLDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EtldslActivator.getInstance().getInjector("org.etl_modeling.etldsl.ETLDsl");
	}

}
