/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.specdsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.etl_modeling.specdsl.ui.internal.SpecdslActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpecDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SpecdslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SpecdslActivator activator = SpecdslActivator.getInstance();
		return activator != null ? activator.getInjector(SpecdslActivator.ORG_ETL_MODELING_SPECDSL_SPECDSL) : null;
	}

}
