/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.etldsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.etl_modeling.etldsl.ETLDslRuntimeModule;
import org.etl_modeling.etldsl.ETLDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ETLDslIdeSetup extends ETLDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ETLDslRuntimeModule(), new ETLDslIdeModule()));
	}
	
}
