/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.etldsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.etl_modeling.etldsl.parser.antlr.internal.InternalETLDslParser;
import org.etl_modeling.etldsl.services.ETLDslGrammarAccess;

public class ETLDslParser extends AbstractAntlrParser {

	@Inject
	private ETLDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalETLDslParser createParser(XtextTokenStream stream) {
		return new InternalETLDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "logpackage";
	}

	public ETLDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ETLDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
