/*
 * generated by Xtext 2.22.0
 */
package org.etl_modeling.specdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.etl_modeling.specdsl.SpecDslRuntimeModule;
import org.etl_modeling.specdsl.SpecDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SpecDslIdeSetup extends SpecDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SpecDslRuntimeModule(), new SpecDslIdeModule()));
	}
	
}
